export default {
    LAYOUT_EDITOR: 'LAYOUT_EDITOR',
    ATTRIBUTE_EDITOR: 'ATTRIBUTE_EDITOR',
    STYLE_EDITOR: 'STYLE_EDITOR',
    ALL_PROPERTY_EDITOR: 'ALL_PROPERTY_EDITOR',
    COMPONENT_PROPETIES_EDITOR: 'COMPONENT_PROPETIES_EDITOR',
    COMPONENT_OUTLINE: 'COMPONENT_OUTLINE',
    COMPONENT_PICKER: 'COMPONENT_PICKER',
    COMPONENT_EDIT_TOOL: 'COMPONENT_EDIT_TOOL',
    UNDO_HISTORY: 'UNDO_HISTORY',
    FORM_EDITOR: 'FORM_EDITOR',
    PLUGINS: {
        COMPILE_FUNCTION: 'COMPILE_FUNCTION',
        COMPONENT_PICKER_VIEW: 'COMPONENT_PICKER_VIEW',
        BUILD_COMPONENT: 'BUILD_COMPONENT',
        DROP_TO_LAYOUT_EDITOR: 'DROP_TO_LAYOUT_EDITOR',
        PROJECT_EXPLORER:'PROJECT_EXPLORER',
        LOAD_CONTENT_DATA:'LOAD_CONTENT_DATA'
    }
}