export default {
    LAYOUT_EDITOR: 'LAYOUT_EDITOR',
    ATTRIBUTE_EDITOR: 'ATTRIBUTE_EDITOR',
    EVENT_EDITOR: 'EVENT_EDITOR',
    STYLE_EDITOR: 'STYLE_EDITOR',
    ALL_PROPERTY_EDITOR: 'ALL_PROPERTY_EDITOR',
    COMPONENT_PROPETIES_EDITOR: 'COMPONENT_PROPETIES_EDITOR',
    COMPONENT_OUTLINE: 'COMPONENT_OUTLINE',
    COMPONENT_PICKER: 'COMPONENT_PICKER',
    CMD_TOOL: 'CMD_TOOL',
    UNDO_HISTORY: 'UNDO_HISTORY',
    FORM_EDITOR: 'FORM_EDITOR',
    HAS_CMD_EDITOR:"HAS_CMD_EDITOR",
    PLUGINS: {
        COMPILE_FUNCTION: 'COMPILE_FUNCTION',
        COMPONENT_PICKER_VIEW: 'COMPONENT_PICKER_VIEW',
        BUILD_COMPONENT: 'BUILD_COMPONENT',
        PROJECT_EXPLORER: 'PROJECT_EXPLORER',
        LOAD_CONTENT_DATA: 'LOAD_CONTENT_DATA',
        SAVE_CONTENT_DATA: 'SAVE_CONTENT_DATA'
    },
    CLIPBOARD: {
        COMPONENTS: 'COMPONENTS'
    },
    APP:'ABSOL_FORM_EDITOR',
    VERSION: '0.6.0',
    STATUS_BAR_ELT: 'STATUS_BAR_ELT'
}