

export function queryURL(fontNames) {
    return 'https://fonts.googleapis.com/css?family=' + fontNames.join('_') + '&display=swap';
}

export var FONT_NAMES = ["Alegreya",
    "Alegreya+SC",
    "Alegreya+Sans",
    "Alegreya+Sans+SC",
    "Alfa+Slab+One",
    "Amatic+SC",
    "Andika",
    "Anton",
    "Archivo",
    "Archivo+Narrow",
    "Arima+Madurai",
    "Arimo",
    "Arsenal",
    "Asap",
    "Asap+Condensed",
    "Athiti",
    "Bahianita",
    "Bai+Jamjuree",
    "Baloo",
    "Baloo+Bhai",
    "Baloo+Bhaijaan",
    "Baloo+Bhaina",
    "Baloo+Chettan",
    "Baloo+Da",
    "Baloo+Paaji",
    "Baloo+Tamma",
    "Baloo+Tammudu",
    "Baloo+Thambi",
    "Bangers",
    "Barlow",
    "Barlow+Condensed",
    "Barlow+Semi+Condensed",
    "Barriecito",
    "Be+Vietnam",
    "Bevan",
    "Big+Shoulders+Display",
    "Big+Shoulders+Text",
    "Bungee",
    "Bungee+Hairline",
    "Bungee+Inline",
    "Bungee+Outline",
    "Bungee+Shade",
    "Cabin",
    "Cabin+Condensed",
    "Chakra+Petch",
    "Charm",
    "Charmonman",
    "Chonburi",
    "Coiny",
    "Comfortaa",
    "Cormorant",
    "Cormorant+Garamond",
    "Cormorant+Infant",
    "Cormorant+SC",
    "Cormorant+Unicase",
    "Cormorant+Upright",
    "Cousine",
    "Crimson+Pro",
    "Cuprum",
    "Dancing+Script",
    "Darker+Grotesque",
    "David+Libre",
    "Dosis",
    "EB+Garamond",
    "Encode+Sans",
    "Encode+Sans+Condensed",
    "Encode+Sans+Expanded",
    "Encode+Sans+Semi+Condensed",
    "Encode+Sans+Semi+Expanded",
    "Exo",
    "Exo+2",
    "Fahkwang",
    "Farsan",
    "Faustina",
    "Fira+Sans",
    "Fira+Sans+Condensed",
    "Fira+Sans+Extra+Condensed",
    "Francois+One",
    "Grenze",
    "Hepta+Slab",
    "IBM+Plex+Mono",
    "IBM+Plex+Sans",
    "IBM+Plex+Sans+Condensed",
    "IBM+Plex+Serif",
    "Inconsolata",
    "Itim",
    "Josefin+Sans",
    "Judson",
    "Jura",
    "K2D",
    "Kanit",
    "KoHo",
    "Kodchasan",
    "Krub",
    "Lalezar",
    "Lemonada",
    "Lexend+Deca",
    "Lexend+Exa",
    "Lexend+Giga",
    "Lexend+Mega",
    "Lexend+Peta",
    "Lexend+Tera",
    "Lexend+Zetta",
    "Literata",
    "Livvic",
    "Lobster",
    "Lora",
    "M+PLUS+1p",
    "M+PLUS+Rounded+1c",
    "Maitree",
    "Major+Mono+Display",
    "Mali",
    "Manuale",
    "Markazi+Text",
    "Maven+Pro",
    "Merriweather",
    "Metrophobic",
    "Mitr",
    "Montserrat",
    "Montserrat+Alternates",
    "Muli",
    "Niramit",
    "Noticia+Text",
    "Noto+Sans",
    "Noto+Sans+SC",
    "Noto+Serif",
    "Noto+Serif+SC",
    "Noto+Serif+TC",
    "Nunito",
    "Nunito+Sans",
    "Old+Standard+TT",
    "Open+Sans",
    "Open+Sans+Condensed:300",
    "Oswald",
    "Pacifico",
    "Pangolin",
    "Patrick+Hand",
    "Patrick+Hand+SC",
    "Pattaya",
    "Paytone+One",
    "Philosopher",
    "Play",
    "Playfair+Display",
    "Playfair+Display+SC",
    "Podkova",
    "Prata",
    "Pridi",
    "Prompt",
    "Quicksand",
    "Roboto",
    "Roboto+Condensed",
    "Roboto+Mono",
    "Roboto+Slab",
    "Rokkitt",
    "Rosario",
    "Saira",
    "Saira+Condensed",
    "Saira+Extra+Condensed",
    "Saira+Semi+Condensed",
    "Saira+Stencil+One",
    "Sarabun",
    "Sawarabi+Gothic",
    "Sedgwick+Ave",
    "Sedgwick+Ave+Display",
    "Sigmar+One",
    "Source+Code+Pro",
    "Source+Sans+Pro",
    "Space+Mono",
    "Spectral",
    "Spectral+SC",
    "Sriracha",
    "Srisakdi",
    "Taviraj",
    "Thasadith",
    "Tinos",
    "Trirong",
    "VT323",
    "Varela+Round",
    "Vollkorn",
    "Vollkorn+SC",
    "Yanone+Kaffeesatz",
    "Yeseva+One"
];

export var FONT_FACES = [
    "'Open Sans', sans-serif",
    "'Roboto', sans-serif",
    "'Big Shoulders Text', cursive",
    "'Montserrat', sans-serif",
    "'Oswald', sans-serif",
    "'Source Sans Pro', sans-serif",
    "'Roboto Condensed', sans-serif",
    "'Literata', serif",
    "'Roboto Mono', monospace",
    "'Roboto Slab', serif",
    "'Merriweather', serif",
    "'Noto Sans', sans-serif",
    "'Lora', serif",
    "'Muli', sans-serif",
    "'Open Sans Condensed', sans-serif",
    "'Playfair Display', serif",
    "'Nunito', sans-serif",
    "'Noto Serif', serif",
    "'Fira Sans', sans-serif",
    "'Inconsolata', monospace",
    "'Dosis', sans-serif",
    "'Nunito Sans', sans-serif",
    "'Arimo', sans-serif",
    "'Quicksand', sans-serif",
    "'Cabin', sans-serif",
    "'Josefin Sans', sans-serif",
    "'Varela Round', sans-serif",
    "'Anton', sans-serif",
    "'Lobster', cursive",
    "'Yanone Kaffeesatz', sans-serif",
    "'Source Code Pro', monospace",
    "'Baloo Bhai', cursive",
    "'Barlow', sans-serif",
    "'Dancing Script', cursive",
    "'Pacifico', cursive",
    "'Exo 2', sans-serif",
    "'Barlow Semi Condensed', sans-serif",
    "'EB Garamond', serif",
    "'Archivo Narrow', sans-serif",
    "'Asap', sans-serif",
    "'Comfortaa', cursive",
    "'Barlow Condensed', sans-serif",
    "'IBM Plex Sans', sans-serif",
    "'Maven Pro', sans-serif",
    "'Play', sans-serif",
    "'Exo', sans-serif",
    "'Amatic SC', cursive",
    "'Kanit', sans-serif",
    "'Fira Sans Condensed', sans-serif",
    "'Noto Sans SC', sans-serif",
    "'Vollkorn', serif",
    "'Prompt', sans-serif",
    "'Rokkitt', serif",
    "'Cuprum', sans-serif",
    "'Alegreya Sans', sans-serif",
    "'Francois One', sans-serif",
    "'Cormorant Garamond', serif",
    "'Alegreya', serif",
    "'Alfa Slab One', cursive",
    "'Noticia Text', serif",
    "'Saira Extra Condensed', sans-serif",
    "'Old Standard TT', serif",
    "'Tinos', serif",
    "'Fira Sans Extra Condensed', sans-serif",
    "'IBM Plex Serif', serif",
    "'Patrick Hand', cursive",
    "'M PLUS 1p', sans-serif",
    "'Prata', serif",
    "'Philosopher', sans-serif",
    "'Saira Semi Condensed', sans-serif",
    "'Archivo', sans-serif",
    "'Big Shoulders Display', cursive",
    "'Bangers', cursive",
    "'Playfair Display SC', serif",
    "'Cabin Condensed', sans-serif",
    "'Paytone One', sans-serif",
    "'Montserrat Alternates', sans-serif",
    "'Taviraj', serif",
    "'Spectral', serif",
    "'Lalezar', cursive",
    "'Asap Condensed', sans-serif",
    "'M PLUS Rounded 1c', sans-serif",
    "'Sigmar One', cursive",
    "'Saira', sans-serif",
    "'Pridi', serif",
    "'Mitr', sans-serif",
    "'Baloo', cursive",
    "'Cormorant', serif",
    "'Sarabun', sans-serif",
    "'Saira Condensed', sans-serif",
    "'Be Vietnam', sans-serif",
    "'Yeseva One', cursive",
    "'Lexend Peta', sans-serif",
    "'Alegreya Sans SC', sans-serif",
    "'IBM Plex Mono', monospace",
    "'Jura', sans-serif",
    "'Bevan', cursive",
    "'Lexend Exa', sans-serif",
    "'Sawarabi Gothic', sans-serif",
    "'Cousine', monospace",
    "'Markazi Text', serif",
    "'VT323', monospace",
    "'Baloo Bhaina', cursive",
    "'Space Mono', monospace",
    "'Encode Sans', sans-serif",
    "'Encode Sans Semi Expanded', sans-serif",
    "'Arima Madurai', cursive",
    "'Lexend Deca', sans-serif",
    "'Lexend Tera', sans-serif",
    "'Lexend Giga', sans-serif",
    "'Lexend Zetta', sans-serif",
    "'Lexend Mega', sans-serif",
    "'Arsenal', sans-serif",
    "'Itim', cursive",
    "'Noto Serif SC', serif",
    "'Pangolin', cursive",
    "'Lemonada', cursive",
    "'Encode Sans Condensed', sans-serif",
    "'Bai Jamjuree', sans-serif",
    "'Alegreya SC', serif",
    "'Noto Serif TC', serif",
    "'Judson', serif",
    "'Livvic', sans-serif",
    "'Krub', sans-serif",
    "'Trirong', serif",
    "'Niramit', sans-serif",
    "'Bungee Inline', cursive",
    "'Mali', cursive",
    "'Pattaya', sans-serif",
    "'Rosario', sans-serif",
    "'Bungee', cursive",
    "'Sriracha', cursive",
    "'Metrophobic', sans-serif",
    "'Faustina', serif",
    "'Darker Grotesque', sans-serif",
    "'Encode Sans Expanded', sans-serif",
    "'Chakra Petch', sans-serif",
    "'IBM Plex Sans Condensed', sans-serif",
    "'Maitree', serif",
    "'Baloo Bhaijaan', cursive",
    "'Cormorant Infant', serif",
    "'Saira Stencil One', cursive",
    "'Chonburi', cursive",
    "'Barriecito', cursive",
    "'Bahianita', cursive",
    "'Athiti', sans-serif",
    "'Sedgwick Ave', cursive",
    "'Patrick Hand SC', cursive",
    "'Srisakdi', cursive",
    "'Cormorant SC', serif",
    "'Andika', sans-serif",
    "'Podkova', serif",
    "'Bungee Shade', cursive",
    "'Baloo Da', cursive",
    "'Spectral SC', serif",
    "'Baloo Thambi', cursive",
    "'Baloo Chettan', cursive",
    "'Cormorant Upright', serif",
    "'Encode Sans Semi Condensed', sans-serif",
    "'Charm', cursive",
    "'Baloo Paaji', cursive",
    "'K2D', sans-serif",
    "'Farsan', cursive",
    "'David Libre', serif",
    "'Coiny', cursive",
    "'Baloo Tamma', cursive",
    "'Manuale', serif",
    "'Thasadith', sans-serif",
    "'Vollkorn SC', serif",
    "'Bungee Hairline', cursive",
    "'Kodchasan', sans-serif",
    "'Hepta Slab', serif",
    "'Cormorant Unicase', serif",
    "'Crimson Pro', serif",
    "'Grenze', serif",
    "'Charmonman', cursive",
    "'Baloo Tammudu', cursive",
    "'KoHo', sans-serif",
    "'Major Mono Display', monospace",
    "'Fahkwang', sans-serif",
    "'Bungee Outline', cursive",
    "'Sedgwick Ave Display', cursive"
];

export var FONT_ITEMS = FONT_FACES.map(function (fontFamily) {
    var fontName = fontFamily.match(/\'([^\']+)\'/)[1];
    return {
        text: fontName, value: fontFamily, extendStyle: {
            fontFamily: fontFamily
        }
    }
}, {});

export var FONT_FACES_BY_NAME = FONT_ITEMS.reduce(function (ac, cr) {
    ac[cr.text] = cr.value;
    return ac;
}, {});